
//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-05-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-AH3IE72`, CPU: `AMD Ryzen 3 3100 4-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /home/neurosx/WORKING_WORKSPACE/fennel-solonet-2503UPGRADE/target/release/wbuild/fennel-node-runtime/fennel_node_runtime.wasm
// --pallet
// pallet_identity
// --extrinsic
// 
// --template
// /home/neurosx/WORKING_WORKSPACE/fennel-solonet-2503UPGRADE/scripts/benchmarking/frame-weight-template.hbs
// --output
// /home/neurosx/WORKING_WORKSPACE/fennel-solonet-2503UPGRADE/benchmarks_output/pallet_identity_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_identity`.
pub trait WeightInfo {
	fn create_identity() -> Weight;
	fn revoke_identity() -> Weight;
	fn add_or_update_identity_trait(l: u32, ) -> Weight;
	fn remove_identity_trait(l: u32, ) -> Weight;
	fn revoke_identity_heavy_storage() -> Weight;
	fn add_or_update_long_identity_trait() -> Weight;
	fn add_or_update_many_identity_traits() -> Weight;
	fn remove_identity_trait_heavy_storage() -> Weight;
	fn remove_long_identity_trait() -> Weight;
}

/// Weights for `pallet_identity` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Identity::IdentityNumber` (r:1 w:1)
	/// Proof: `Identity::IdentityNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3517`
		// Minimum execution time: 16_254_000 picoseconds.
		Weight::from_parts(17_073_000, 3517)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `3517`
		// Minimum execution time: 16_415_000 picoseconds.
		Weight::from_parts(17_001_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 1024]`.
	fn add_or_update_identity_trait(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 18_486_000 picoseconds.
		Weight::from_parts(19_555_962, 5553)
			// Standard Error: 329
			.saturating_add(Weight::from_parts(3_852, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 1024]`.
	fn remove_identity_trait(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 17_379_000 picoseconds.
		Weight::from_parts(20_651_638, 3517)
			// Standard Error: 474
			.saturating_add(Weight::from_parts(782, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1145`
		//  Estimated: `3517`
		// Minimum execution time: 34_299_000 picoseconds.
		Weight::from_parts(43_092_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 22_013_000 picoseconds.
		Weight::from_parts(22_958_000, 5553)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_many_identity_traits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `5553`
		// Minimum execution time: 58_293_000 picoseconds.
		Weight::from_parts(67_841_000, 5553)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_identity_trait_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 47_439_000 picoseconds.
		Weight::from_parts(56_402_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 19_872_000 picoseconds.
		Weight::from_parts(23_436_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Identity::IdentityNumber` (r:1 w:1)
	/// Proof: `Identity::IdentityNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `3517`
		// Minimum execution time: 16_254_000 picoseconds.
		Weight::from_parts(17_073_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `3517`
		// Minimum execution time: 16_415_000 picoseconds.
		Weight::from_parts(17_001_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 1024]`.
	fn add_or_update_identity_trait(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 18_486_000 picoseconds.
		Weight::from_parts(19_555_962, 5553)
			// Standard Error: 329
			.saturating_add(Weight::from_parts(3_852, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 1024]`.
	fn remove_identity_trait(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 17_379_000 picoseconds.
		Weight::from_parts(20_651_638, 3517)
			// Standard Error: 474
			.saturating_add(Weight::from_parts(782, 0).saturating_mul(l.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1145`
		//  Estimated: `3517`
		// Minimum execution time: 34_299_000 picoseconds.
		Weight::from_parts(43_092_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 22_013_000 picoseconds.
		Weight::from_parts(22_958_000, 5553)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_many_identity_traits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `5553`
		// Minimum execution time: 58_293_000 picoseconds.
		Weight::from_parts(67_841_000, 5553)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_identity_trait_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 47_439_000 picoseconds.
		Weight::from_parts(56_402_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 19_872_000 picoseconds.
		Weight::from_parts(23_436_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
