
//! Autogenerated weights for `pallet_trust`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-05-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-AH3IE72`, CPU: `AMD Ryzen 3 3100 4-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /home/neurosx/WORKING_WORKSPACE/StandaloneSolochain2503/solochain/target/release/wbuild/solochain-template-runtime/solochain_template_runtime.compact.compressed.wasm
// --pallet
// pallet_trust
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-weight-template.hbs
// --output
// ./pallets/trust/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_trust`.
pub trait WeightInfo {
	fn set_trust_parameter() -> Weight;
	fn issue_trust() -> Weight;
	fn issue_trust_repeatedly(m: u32, ) -> Weight;
	fn revoke_trust() -> Weight;
	fn revoke_trust_from_heavy_storage(m: u32, ) -> Weight;
	fn remove_trust() -> Weight;
	fn remove_trust_from_heavy_storage(m: u32, ) -> Weight;
	fn request_trust() -> Weight;
	fn request_trust_repeatedly(m: u32, ) -> Weight;
	fn remove_revoked_trust() -> Weight;
	fn remove_revoked_trust_heavy_storage(m: u32, ) -> Weight;
	fn cancel_trust_request() -> Weight;
	fn cancel_trust_request_heavy_storage(m: u32, ) -> Weight;
}

/// Weights for `pallet_trust` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Trust::TrustParameterList` (r:0 w:1)
	/// Proof: `Trust::TrustParameterList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	fn set_trust_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_809_000 picoseconds.
		Weight::from_parts(14_247_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn issue_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 16_299_000 picoseconds.
		Weight::from_parts(19_026_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn issue_trust_repeatedly(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `932`
		//  Estimated: `3565`
		// Minimum execution time: 16_236_000 picoseconds.
		Weight::from_parts(25_269_230, 3565)
			// Standard Error: 618
			.saturating_add(Weight::from_parts(15_672, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn revoke_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 16_425_000 picoseconds.
		Weight::from_parts(21_537_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 100000]`.
	fn revoke_trust_from_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1825`
		//  Estimated: `3565`
		// Minimum execution time: 16_371_000 picoseconds.
		Weight::from_parts(27_449_014, 3565)
			// Standard Error: 126
			.saturating_add(Weight::from_parts(2_078, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 20_655_000 picoseconds.
		Weight::from_parts(23_058_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn remove_trust_from_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1037`
		//  Estimated: `3565`
		// Minimum execution time: 19_881_000 picoseconds.
		Weight::from_parts(39_805_090, 3565)
			// Standard Error: 1_781
			.saturating_add(Weight::from_parts(16_482, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn request_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 16_128_000 picoseconds.
		Weight::from_parts(19_863_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn request_trust_repeatedly(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `930`
		//  Estimated: `3565`
		// Minimum execution time: 16_137_000 picoseconds.
		Weight::from_parts(28_166_507, 3565)
			// Standard Error: 1_261
			.saturating_add(Weight::from_parts(29_249, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_revoked_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 20_601_000 picoseconds.
		Weight::from_parts(32_715_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn remove_revoked_trust_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1037`
		//  Estimated: `3565`
		// Minimum execution time: 20_889_000 picoseconds.
		Weight::from_parts(40_107_370, 3565)
			// Standard Error: 1_721
			.saturating_add(Weight::from_parts(21_684, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_trust_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3565`
		// Minimum execution time: 21_852_000 picoseconds.
		Weight::from_parts(34_038_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn cancel_trust_request_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1017`
		//  Estimated: `3565`
		// Minimum execution time: 19_701_000 picoseconds.
		Weight::from_parts(34_817_161, 3565)
			// Standard Error: 1_255
			.saturating_add(Weight::from_parts(20_346, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Trust::TrustParameterList` (r:0 w:1)
	/// Proof: `Trust::TrustParameterList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	fn set_trust_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_809_000 picoseconds.
		Weight::from_parts(14_247_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn issue_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 16_299_000 picoseconds.
		Weight::from_parts(19_026_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn issue_trust_repeatedly(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `932`
		//  Estimated: `3565`
		// Minimum execution time: 16_236_000 picoseconds.
		Weight::from_parts(25_269_230, 3565)
			// Standard Error: 618
			.saturating_add(Weight::from_parts(15_672, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn revoke_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 16_425_000 picoseconds.
		Weight::from_parts(21_537_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 100000]`.
	fn revoke_trust_from_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1825`
		//  Estimated: `3565`
		// Minimum execution time: 16_371_000 picoseconds.
		Weight::from_parts(27_449_014, 3565)
			// Standard Error: 126
			.saturating_add(Weight::from_parts(2_078, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 20_655_000 picoseconds.
		Weight::from_parts(23_058_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn remove_trust_from_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1037`
		//  Estimated: `3565`
		// Minimum execution time: 19_881_000 picoseconds.
		Weight::from_parts(39_805_090, 3565)
			// Standard Error: 1_781
			.saturating_add(Weight::from_parts(16_482, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn request_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 16_128_000 picoseconds.
		Weight::from_parts(19_863_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn request_trust_repeatedly(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `930`
		//  Estimated: `3565`
		// Minimum execution time: 16_137_000 picoseconds.
		Weight::from_parts(28_166_507, 3565)
			// Standard Error: 1_261
			.saturating_add(Weight::from_parts(29_249, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_revoked_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 20_601_000 picoseconds.
		Weight::from_parts(32_715_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn remove_revoked_trust_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1037`
		//  Estimated: `3565`
		// Minimum execution time: 20_889_000 picoseconds.
		Weight::from_parts(40_107_370, 3565)
			// Standard Error: 1_721
			.saturating_add(Weight::from_parts(21_684, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_trust_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3565`
		// Minimum execution time: 21_852_000 picoseconds.
		Weight::from_parts(34_038_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[0, 1000]`.
	fn cancel_trust_request_heavy_storage(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1017`
		//  Estimated: `3565`
		// Minimum execution time: 19_701_000 picoseconds.
		Weight::from_parts(34_817_161, 3565)
			// Standard Error: 1_255
			.saturating_add(Weight::from_parts(20_346, 0).saturating_mul(m.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
