
//! Autogenerated weights for `pallet_trust`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-04-29, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-AH3IE72`, CPU: `AMD Ryzen 3 3100 4-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_trust
// --extrinsic=*
// --steps=20
// --repeat=5
// --template=./scripts/templates/weight-template.hbs
// --output=./runtime/fennel/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_trust`.
pub trait WeightInfo {
	fn set_trust_parameter() -> Weight;
	fn issue_trust() -> Weight;
	fn issue_trust_repeatedly() -> Weight;
	fn revoke_trust() -> Weight;
	fn revoke_trust_from_heavy_storage() -> Weight;
	fn remove_trust() -> Weight;
	fn remove_trust_from_heavy_storage() -> Weight;
	fn request_trust() -> Weight;
	fn request_trust_repeatedly() -> Weight;
	fn remove_revoked_trust() -> Weight;
	fn remove_revoked_trust_heavy_storage() -> Weight;
	fn cancel_trust_request() -> Weight;
	fn cancel_trust_request_heavy_storage() -> Weight;
}

/// Weights for `pallet_trust` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Trust::TrustParameterList` (r:0 w:1)
	/// Proof: `Trust::TrustParameterList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	fn set_trust_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_919_000 picoseconds.
		Weight::from_parts(11_646_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn issue_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 15_586_000 picoseconds.
		Weight::from_parts(15_710_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn issue_trust_repeatedly() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1158`
		//  Estimated: `3565`
		// Minimum execution time: 35_972_000 picoseconds.
		Weight::from_parts(41_383_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn revoke_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 24_784_000 picoseconds.
		Weight::from_parts(27_872_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn revoke_trust_from_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2151`
		//  Estimated: `3565`
		// Minimum execution time: 69_072_000 picoseconds.
		Weight::from_parts(77_086_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 19_404_000 picoseconds.
		Weight::from_parts(20_147_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_trust_from_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1263`
		//  Estimated: `3565`
		// Minimum execution time: 49_097_000 picoseconds.
		Weight::from_parts(50_211_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn request_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 15_417_000 picoseconds.
		Weight::from_parts(20_062_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn request_trust_repeatedly() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156`
		//  Estimated: `3565`
		// Minimum execution time: 39_171_000 picoseconds.
		Weight::from_parts(50_287_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_revoked_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 19_395_000 picoseconds.
		Weight::from_parts(20_757_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_revoked_trust_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1263`
		//  Estimated: `3565`
		// Minimum execution time: 39_123_000 picoseconds.
		Weight::from_parts(40_666_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_trust_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3565`
		// Minimum execution time: 17_664_000 picoseconds.
		Weight::from_parts(18_815_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_trust_request_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156`
		//  Estimated: `3565`
		// Minimum execution time: 34_669_000 picoseconds.
		Weight::from_parts(35_840_000, 3565)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Trust::TrustParameterList` (r:0 w:1)
	/// Proof: `Trust::TrustParameterList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	fn set_trust_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_919_000 picoseconds.
		Weight::from_parts(11_646_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn issue_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 15_586_000 picoseconds.
		Weight::from_parts(15_710_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn issue_trust_repeatedly() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1158`
		//  Estimated: `3565`
		// Minimum execution time: 35_972_000 picoseconds.
		Weight::from_parts(41_383_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn revoke_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 24_784_000 picoseconds.
		Weight::from_parts(27_872_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn revoke_trust_from_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2151`
		//  Estimated: `3565`
		// Minimum execution time: 69_072_000 picoseconds.
		Weight::from_parts(77_086_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 19_404_000 picoseconds.
		Weight::from_parts(20_147_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustIssuance` (r:1 w:1)
	/// Proof: `Trust::TrustIssuance` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentIssued` (r:1 w:1)
	/// Proof: `Trust::CurrentIssued` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_trust_from_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1263`
		//  Estimated: `3565`
		// Minimum execution time: 49_097_000 picoseconds.
		Weight::from_parts(50_211_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn request_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3565`
		// Minimum execution time: 15_417_000 picoseconds.
		Weight::from_parts(20_062_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn request_trust_repeatedly() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156`
		//  Estimated: `3565`
		// Minimum execution time: 39_171_000 picoseconds.
		Weight::from_parts(50_287_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_revoked_trust() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `157`
		//  Estimated: `3565`
		// Minimum execution time: 19_395_000 picoseconds.
		Weight::from_parts(20_757_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRevocation` (r:1 w:1)
	/// Proof: `Trust::TrustRevocation` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRevoked` (r:1 w:1)
	/// Proof: `Trust::CurrentRevoked` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn remove_revoked_trust_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1263`
		//  Estimated: `3565`
		// Minimum execution time: 39_123_000 picoseconds.
		Weight::from_parts(40_666_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_trust_request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `155`
		//  Estimated: `3565`
		// Minimum execution time: 17_664_000 picoseconds.
		Weight::from_parts(18_815_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Trust::TrustRequestList` (r:1 w:1)
	/// Proof: `Trust::TrustRequestList` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `Trust::CurrentRequests` (r:1 w:1)
	/// Proof: `Trust::CurrentRequests` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_trust_request_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1156`
		//  Estimated: `3565`
		// Minimum execution time: 34_669_000 picoseconds.
		Weight::from_parts(35_840_000, 3565)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
