
//! Autogenerated weights for `pallet_validator_manager`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-04-29, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-AH3IE72`, CPU: `AMD Ryzen 3 3100 4-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_validator_manager
// --extrinsic=*
// --steps=20
// --repeat=5
// --template=./scripts/templates/weight-template.hbs
// --output=./runtime/fennel/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_validator_manager`.
pub trait WeightInfo {
	fn register_validators(v: u32, ) -> Weight;
	fn remove_validator() -> Weight;
}

/// Weights for `pallet_validator_manager` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ValidatorManager::ValidatorsToAdd` (r:1 w:1)
	/// Proof: `ValidatorManager::ValidatorsToAdd` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `v` is `[1, 100]`.
	fn register_validators(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `64`
		//  Estimated: `1549`
		// Minimum execution time: 13_540_000 picoseconds.
		Weight::from_parts(13_688_142, 1549)
			// Standard Error: 19_799
			.saturating_add(Weight::from_parts(230_612, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorManager::ValidatorsToRemove` (r:1 w:1)
	/// Proof: `ValidatorManager::ValidatorsToRemove` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `43`
		//  Estimated: `1528`
		// Minimum execution time: 10_250_000 picoseconds.
		Weight::from_parts(10_776_000, 1528)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ValidatorManager::ValidatorsToAdd` (r:1 w:1)
	/// Proof: `ValidatorManager::ValidatorsToAdd` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `v` is `[1, 100]`.
	fn register_validators(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `64`
		//  Estimated: `1549`
		// Minimum execution time: 13_540_000 picoseconds.
		Weight::from_parts(13_688_142, 1549)
			// Standard Error: 19_799
			.saturating_add(Weight::from_parts(230_612, 0).saturating_mul(v.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ValidatorManager::ValidatorsToRemove` (r:1 w:1)
	/// Proof: `ValidatorManager::ValidatorsToRemove` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn remove_validator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `43`
		//  Estimated: `1528`
		// Minimum execution time: 10_250_000 picoseconds.
		Weight::from_parts(10_776_000, 1528)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
