
//! Autogenerated weights for `pallet_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-04-29, STEPS: `20`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-AH3IE72`, CPU: `AMD Ryzen 3 3100 4-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_identity
// --extrinsic=*
// --steps=20
// --repeat=5
// --template=./scripts/templates/weight-template.hbs
// --output=./runtime/fennel/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_identity`.
pub trait WeightInfo {
	fn create_identity() -> Weight;
	fn revoke_identity() -> Weight;
	fn revoke_identity_heavy_storage() -> Weight;
	fn add_or_update_identity_trait() -> Weight;
	fn add_or_update_long_identity_trait() -> Weight;
	fn add_or_update_many_identity_traits() -> Weight;
	fn remove_identity_trait() -> Weight;
	fn remove_identity_trait_heavy_storage() -> Weight;
	fn remove_long_identity_trait() -> Weight;
}

/// Weights for `pallet_identity` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Identity::IdentityNumber` (r:1 w:1)
	/// Proof: `Identity::IdentityNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1190`
		//  Estimated: `3517`
		// Minimum execution time: 30_920_000 picoseconds.
		Weight::from_parts(35_700_000, 3517)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `3517`
		// Minimum execution time: 15_853_000 picoseconds.
		Weight::from_parts(16_360_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1150`
		//  Estimated: `3517`
		// Minimum execution time: 37_137_000 picoseconds.
		Weight::from_parts(43_516_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 18_410_000 picoseconds.
		Weight::from_parts(22_778_000, 5553)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 20_786_000 picoseconds.
		Weight::from_parts(21_897_000, 5553)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_many_identity_traits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `5553`
		// Minimum execution time: 61_032_000 picoseconds.
		Weight::from_parts(294_736_000, 5553)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 16_317_000 picoseconds.
		Weight::from_parts(16_552_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_identity_trait_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 56_946_000 picoseconds.
		Weight::from_parts(244_916_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 18_538_000 picoseconds.
		Weight::from_parts(18_874_000, 3517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Identity::IdentityNumber` (r:1 w:1)
	/// Proof: `Identity::IdentityNumber` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1190`
		//  Estimated: `3517`
		// Minimum execution time: 30_920_000 picoseconds.
		Weight::from_parts(35_700_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `3517`
		// Minimum execution time: 15_853_000 picoseconds.
		Weight::from_parts(16_360_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:1)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn revoke_identity_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1150`
		//  Estimated: `3517`
		// Minimum execution time: 37_137_000 picoseconds.
		Weight::from_parts(43_516_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 18_410_000 picoseconds.
		Weight::from_parts(22_778_000, 5553)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `5553`
		// Minimum execution time: 20_786_000 picoseconds.
		Weight::from_parts(21_897_000, 5553)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:1 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn add_or_update_many_identity_traits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `715`
		//  Estimated: `5553`
		// Minimum execution time: 61_032_000 picoseconds.
		Weight::from_parts(294_736_000, 5553)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 16_317_000 picoseconds.
		Weight::from_parts(16_552_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_identity_trait_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 56_946_000 picoseconds.
		Weight::from_parts(244_916_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Identity::IdentityList` (r:1 w:0)
	/// Proof: `Identity::IdentityList` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::IdentityTraitList` (r:0 w:1)
	/// Proof: `Identity::IdentityTraitList` (`max_values`: None, `max_size`: Some(2088), added: 4563, mode: `MaxEncodedLen`)
	fn remove_long_identity_trait() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `142`
		//  Estimated: `3517`
		// Minimum execution time: 18_538_000 picoseconds.
		Weight::from_parts(18_874_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
