[package]
name = "fennel-node"
description = "A solochain node implementation of Fennel Protocol."
version = "0.0.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
clap = { features = ["derive"], workspace = true }
futures = { features = ["thread-pool"], workspace = true }
jsonrpsee = { features = ["server"], workspace = true }

# substrate client
sc-cli.default-features = true
sc-cli.workspace = true
sp-core.default-features = true
sp-core.workspace = true
sc-executor.default-features = true
sc-executor.workspace = true
sc-network.default-features = true
sc-network.workspace = true
sc-service.default-features = true
sc-service.workspace = true
sc-telemetry.default-features = true
sc-telemetry.workspace = true
sc-transaction-pool-api.default-features = true
sc-transaction-pool-api.workspace = true
sc-transaction-pool.default-features = true
sc-transaction-pool.workspace = true
sc-offchain.default-features = true
sc-offchain.workspace = true
sc-consensus-aura.default-features = true
sc-consensus-aura.workspace = true
sp-consensus-aura.default-features = true
sp-consensus-aura.workspace = true
sc-consensus.default-features = true
sc-consensus.workspace = true
sc-consensus-grandpa.default-features = true
sc-consensus-grandpa.workspace = true
sc-client-api.default-features = true
sc-client-api.workspace = true
sc-basic-authorship.default-features = true
sc-basic-authorship.workspace = true




# substrate primitives
sp-runtime.default-features = true
sp-runtime.workspace = true
sp-io.default-features = true
sp-io.workspace = true
sp-timestamp.default-features = true
sp-timestamp.workspace = true
sp-inherents.default-features = true
sp-inherents.workspace = true
sp-keyring.default-features = true
sp-keyring.workspace = true
sp-api.default-features = true
sp-api.workspace = true
sp-blockchain.default-features = true
sp-blockchain.workspace = true
sp-block-builder.default-features = true
sp-block-builder.workspace = true
sp-genesis-builder.default-features = true
sp-genesis-builder.workspace = true

# frame and pallets
frame-system.default-features = true
frame-system.workspace = true
pallet-transaction-payment.default-features = true
pallet-transaction-payment.workspace = true
pallet-transaction-payment-rpc.default-features = true
pallet-transaction-payment-rpc.workspace = true
substrate-frame-rpc-system.default-features = true
substrate-frame-rpc-system.workspace = true
frame-metadata-hash-extension.default-features = true
frame-metadata-hash-extension.workspace = true


# These dependencies are used for runtime benchmarking
frame-benchmarking-cli = { workspace = true, default-features = false, optional = true }

# Local Dependencies
fennel-node-runtime = { path = "../runtime/fennel" }












[build-dependencies]
substrate-build-script-utils.default-features = true
substrate-build-script-utils.workspace = true

[features]
default = []

# runtime code paths for benches (no CLI)
runtime-benchmarks = [
	"fennel-node-runtime/runtime-benchmarks",
	"sc-service/runtime-benchmarks",
]

# CLI subcommand (no parachain deps)
bench-cli = [
	"dep:frame-benchmarking-cli",
	"frame-benchmarking-cli/rocksdb",   # needed for expose_db/expose_storage
]

# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"frame-system/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"fennel-node-runtime/try-runtime",
	"sp-runtime/try-runtime",
]
