
//! Autogenerated weights for `pallet_infostratus`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2025-05-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-AH3IE72`, CPU: `AMD Ryzen 3 3100 4-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// /home/neurosx/WORKING_WORKSPACE/fennel-solonet-2503UPGRADE/target/release/wbuild/fennel-node-runtime/fennel_node_runtime.wasm
// --pallet
// pallet_infostratus
// --extrinsic
// 
// --template
// /home/neurosx/WORKING_WORKSPACE/fennel-solonet-2503UPGRADE/scripts/benchmarking/frame-weight-template.hbs
// --output
// /home/neurosx/WORKING_WORKSPACE/fennel-solonet-2503UPGRADE/benchmarks_output/pallet_infostratus_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_infostratus`.
pub trait WeightInfo {
	fn create_submission_entry() -> Weight;
	fn create_submission_entry_heavy_storage() -> Weight;
	fn request_submission_assignment() -> Weight;
	fn request_submission_assignment_heavy_storage() -> Weight;
}

/// Weights for `pallet_infostratus` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_submission_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `4764`
		// Minimum execution time: 45_153_000 picoseconds.
		Weight::from_parts(49_851_000, 4764)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_submission_entry_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2174`
		//  Estimated: `4764`
		// Minimum execution time: 98_514_000 picoseconds.
		Weight::from_parts(102_626_000, 4764)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Infostratus::AssignmentsList` (r:1 w:1)
	/// Proof: `Infostratus::AssignmentsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	fn request_submission_assignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `115`
		//  Estimated: `4764`
		// Minimum execution time: 55_412_000 picoseconds.
		Weight::from_parts(76_958_000, 4764)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Infostratus::AssignmentsList` (r:1 w:1)
	/// Proof: `Infostratus::AssignmentsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	fn request_submission_assignment_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4188`
		//  Estimated: `4764`
		// Minimum execution time: 134_729_000 picoseconds.
		Weight::from_parts(152_604_000, 4764)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_submission_entry() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `4764`
		// Minimum execution time: 45_153_000 picoseconds.
		Weight::from_parts(49_851_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn create_submission_entry_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2174`
		//  Estimated: `4764`
		// Minimum execution time: 98_514_000 picoseconds.
		Weight::from_parts(102_626_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Infostratus::AssignmentsList` (r:1 w:1)
	/// Proof: `Infostratus::AssignmentsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	fn request_submission_assignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `115`
		//  Estimated: `4764`
		// Minimum execution time: 55_412_000 picoseconds.
		Weight::from_parts(76_958_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Infostratus::SubmissionsList` (r:1 w:1)
	/// Proof: `Infostratus::SubmissionsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Infostratus::AssignmentsList` (r:1 w:1)
	/// Proof: `Infostratus::AssignmentsList` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	fn request_submission_assignment_heavy_storage() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4188`
		//  Estimated: `4764`
		// Minimum execution time: 134_729_000 picoseconds.
		Weight::from_parts(152_604_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
