
//! Autogenerated weights for pallet_signal
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-08-26, STEPS: `100`, REPEAT: 100, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Seans-Mac-Mini`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_signal
// --extrinsic=*
// --steps=100
// --repeat=100
// --template=./scripts/templates/weight-template.hbs
// --output=./runtime/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_signal.
pub trait WeightInfo {
	fn set_signal_parameter() -> Weight;
	fn send_rating_signal() -> Weight;
	fn update_rating_signal() -> Weight;
	fn revoke_rating_signal() -> Weight;
	fn send_signal() -> Weight;
	fn send_service_signal() -> Weight;
}

/// Weights for pallet_signal using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: `Signal::SignalParameterList` (r:0 w:1)
	// Proof: `Signal::SignalParameterList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	fn set_signal_parameter() -> Weight {
		// Minimum execution time: 6_000 nanoseconds.
		Weight::from_ref_time(6_000_000)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: `Signal::RatingSignalList` (r:1 w:1)
	// Proof: `Signal::RatingSignalList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `Balances::Locks` (r:1 w:1)
	// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	// Storage: `Balances::Freezes` (r:1 w:0)
	// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn send_rating_signal() -> Weight {
		// Minimum execution time: 73_000 nanoseconds.
		Weight::from_ref_time(80_000_000)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `Signal::RatingSignalList` (r:1 w:1)
	// Proof: `Signal::RatingSignalList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Balances::Locks` (r:1 w:1)
	// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	// Storage: `Balances::Freezes` (r:1 w:0)
	// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn update_rating_signal() -> Weight {
		// Minimum execution time: 71_000 nanoseconds.
		Weight::from_ref_time(76_000_000)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: `Signal::RatingSignalList` (r:1 w:1)
	// Proof: `Signal::RatingSignalList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Balances::Locks` (r:1 w:1)
	// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	// Storage: `Balances::Freezes` (r:1 w:0)
	// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn revoke_rating_signal() -> Weight {
		// Minimum execution time: 72_000 nanoseconds.
		Weight::from_ref_time(78_000_000)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn send_signal() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(12_000_000)
	}
	fn send_service_signal() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(12_000_000)
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: `Signal::SignalParameterList` (r:0 w:1)
	// Proof: `Signal::SignalParameterList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	fn set_signal_parameter() -> Weight {
		// Minimum execution time: 6_000 nanoseconds.
		Weight::from_ref_time(6_000_000)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: `Signal::RatingSignalList` (r:1 w:1)
	// Proof: `Signal::RatingSignalList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `Balances::Locks` (r:1 w:1)
	// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	// Storage: `Balances::Freezes` (r:1 w:0)
	// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn send_rating_signal() -> Weight {
		// Minimum execution time: 73_000 nanoseconds.
		Weight::from_ref_time(80_000_000)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	// Storage: `Signal::RatingSignalList` (r:1 w:1)
	// Proof: `Signal::RatingSignalList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Balances::Locks` (r:1 w:1)
	// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	// Storage: `Balances::Freezes` (r:1 w:0)
	// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn update_rating_signal() -> Weight {
		// Minimum execution time: 71_000 nanoseconds.
		Weight::from_ref_time(76_000_000)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	// Storage: `Signal::RatingSignalList` (r:1 w:1)
	// Proof: `Signal::RatingSignalList` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	// Storage: `Balances::Locks` (r:1 w:1)
	// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	// Storage: `Balances::Freezes` (r:1 w:0)
	// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	// Storage: `System::Account` (r:1 w:1)
	// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn revoke_rating_signal() -> Weight {
		// Minimum execution time: 72_000 nanoseconds.
		Weight::from_ref_time(78_000_000)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn send_signal() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(12_000_000)
	}
	fn send_service_signal() -> Weight {
		// Minimum execution time: 11_000 nanoseconds.
		Weight::from_ref_time(12_000_000)
	}
}
